name: 'Kestra Deploy Flows Action'
description: 'Create, update or delete a list of Flows from a folder recursively'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  directory:
    description: 'Folder containing your resources'
    default: './'
  namespace:
    description: 'force a Namespace to deploy Flows to'
    required: false
  override:
    description: 'to override flows if they already exist or not'
    default: 'false'
  server:
    description: 'URL of your Kestra server'
    required: true
  apiToken:
    description: 'API Token (EE only)'
    required: false
  user:
    description: 'basic auth username'
    required: false
  password:
    description: 'basic auth password'
    required: false
  tenant:
    description: 'Tenant identifier (EE only, when multi-tenancy is enabled)'
    default: "main"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install CLI
      shell: bash
      run: curl -fsSL https://raw.githubusercontent.com/kestra-io/kestractl/main/install-scripts/install.sh | bash

    - name: Run CLI
      shell: bash
      run: |
        OPTS=""
        if [ -n "${{inputs.namespace}}" ]; then
          OPTS="$OPTS --namespace ${{inputs.namespace}}"
        fi
        if [ "${{inputs.override}}" = "true" ]; then
          OPTS="$OPTS --override"
        fi
        if [ -n "${{inputs.apiToken}}" ]; then
          OPTS="$OPTS --token ${{inputs.apiToken}}"
        elif [ -n "${{inputs.user}}" ] && [ -n "${{inputs.password}}" ]; then
          OPTS="$OPTS --user ${{inputs.user}} --password ${{inputs.password}}"
        fi
        ./kestractl flows deploy ${{inputs.directory}} --host ${{inputs.server}} --tenant ${{inputs.tenant}} $OPTS
