name: 'Kestra Deploy Namespace Files Action'
description: 'Deploy Namespace Files from a folder'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  localPath:
    description: 'path to your file or directory containing your files'
    default: './'
  namespacePath:
    description: 'remote Namespace path to deploy your files to (if localPath is a file, then namespacePath should be a file too)'
    required: true
  namespace:
    description: 'Namespace to deploy files to'
    required: true
  override:
    description: 'to override files if they already exist or not'
    default: 'false'
  server:
    description: 'URL of your Kestra server'
    required: true
  apiToken:
    description: 'API Token (EE only)'
    required: false
  user:
    description: 'basic auth username'
    required: false
  password:
    description: 'basic auth password'
    required: false
  tenant:
    description: 'Tenant identifier (EE only, when multi-tenancy is enabled)'
    default: "main"
    required: true
  kestractlVersion:
    description: "version of kestractl (see https://github.com/kestra-io/kestractl)"
    default: '1.0.0-alpha.7'
runs:
  using: "composite"
  steps:
    - name: Install CLI
      shell: bash
      run: curl -fsSL https://raw.githubusercontent.com/kestra-io/kestractl/main/install-scripts/install.sh | VERSION='${{inputs.kestractlVersion}}' INSTALL_DIR='./' bash

    - name: Run CLI
      shell: bash
      env:
        # indicate in telemetry that kestractl was called from our action
        KESTRACTL_GITHUB_ACTION: true
      run: |
        OPTS=""
        if [ "${{inputs.override}}" = "true" ]; then
          OPTS="$OPTS --override"
        fi
        if [ -n "${{inputs.apiToken}}" ]; then
          OPTS="$OPTS --token ${{inputs.apiToken}}"
        elif [ -n "${{inputs.user}}" ] && [ -n "${{inputs.password}}" ]; then
          OPTS="$OPTS --user ${{inputs.user}} --password ${{inputs.password}}"
        fi
        ./kestractl nsfiles upload ${{inputs.namespace}} ${{inputs.localPath}} ${{inputs.namespacePath}} --host ${{inputs.server}} --tenant ${{inputs.tenant}} $OPTS
